fos_rest:
    routing_loader:
        default_format: json
        include_format: false
    view:
        view_response_listener: true
        formats:
            json: true
        templating_formats:
            html: true
    format_listener:
        rules:
            - { path: '^/admin', priorities: ['html'], fallback_format: 'html', prefer_extension: false }
            - { path: '^/(%app_locales%)/api', priorities: ['json'], fallback_format: 'json' }
            - { path: '^/(%app_locales%)/news/json', priorities: ['json'], fallback_format: 'json' }
            - { path: '^/(%app_locales%)/event/json', priorities: ['json'], fallback_format: 'json' }       
            - { path: '^/', priorities: ['html'], fallback_format: 'html', prefer_extension: false }

    body_listener:
        enabled: true
    param_fetcher_listener:
        enabled: true
    serializer:
        serialize_null:  true   