twig:
    debug: '%kernel.debug%'
    default_path: '%kernel.project_dir%/templates'
    strict_variables: '%kernel.debug%'
    form_themes:
        - 'form/layout.html.twig'
        - 'form/fields.html.twig'
        - '@SonataMedia/Form/media_widgets.html.twig'
        - '@FOSCKEditor/Form/ckeditor_widget.html.twig'
        - '@SonataFormatter/Form/formatter.html.twig'
        
     